// Cluster
variable "cluster_name" {
  description = "The name of the Auto Scaling Group. By default generated by Terraform."
}

// aws_launch_configuration
variable "ami_id" {
  description = "The EC2 Image ID of the instance"
}

variable "iam_instance_profile" {
  description = "The IAM Instance Profile to associate with launched instances."
}

variable "security_group_id" {
  description = " A list of associated Security Group IDS."
}

variable "user_data" {
  description = "The User Data of the instance."
}

variable "instance_type" {
  description = "The Instance Type of the instance to launch."
}

// aws_autoscaling_group
variable "cluster_min_size" {
  description = "The minimum size of the Auto Scaling Group"
}

variable "cluster_max_size" {
  description = "The maximum size of the Auto Scaling Group"
}

variable "desired_capacity" {
  description = "The number of Amazon EC2 instances that should be running in the group."
}

variable "vpc_zone_identifier" {
  description = "A list of subnets"
  type        = list(string)
}
